// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/operation.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionEnumerable_FunctionType int32

const (
	FunctionEnumerable_UNKNOWN   FunctionEnumerable_FunctionType = 0
	FunctionEnumerable_MAP       FunctionEnumerable_FunctionType = 1  // Lift T -> U, pure
	FunctionEnumerable_FILTER    FunctionEnumerable_FunctionType = 2  // Lift T -> bool, pure
	FunctionEnumerable_FOLD      FunctionEnumerable_FunctionType = 3  // Lift [T] -> U, pure
	FunctionEnumerable_TAKE      FunctionEnumerable_FunctionType = 4  // Nullary, pure
	FunctionEnumerable_TAKEWHILE FunctionEnumerable_FunctionType = 5  // Lift T -> bool, pure
	FunctionEnumerable_TAKEFIRST FunctionEnumerable_FunctionType = 6  // Nullary, returns single, pure
	FunctionEnumerable_TAKELAST  FunctionEnumerable_FunctionType = 7  // pure
	FunctionEnumerable_DROP      FunctionEnumerable_FunctionType = 8  // pure
	FunctionEnumerable_DROPWHILE FunctionEnumerable_FunctionType = 9  // pure
	FunctionEnumerable_FOREACH   FunctionEnumerable_FunctionType = 10 // Lift T -> U, effectful
	FunctionEnumerable_CONCAT    FunctionEnumerable_FunctionType = 11 // pure
	FunctionEnumerable_FLATMAP   FunctionEnumerable_FunctionType = 12 // MAP andthen CONCAT, fn should return enumerable
	FunctionEnumerable_SETALL    FunctionEnumerable_FunctionType = 13 // effectful
	FunctionEnumerable_DELETEALL FunctionEnumerable_FunctionType = 14 // effectful
)

// Enum value maps for FunctionEnumerable_FunctionType.
var (
	FunctionEnumerable_FunctionType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "MAP",
		2:  "FILTER",
		3:  "FOLD",
		4:  "TAKE",
		5:  "TAKEWHILE",
		6:  "TAKEFIRST",
		7:  "TAKELAST",
		8:  "DROP",
		9:  "DROPWHILE",
		10: "FOREACH",
		11: "CONCAT",
		12: "FLATMAP",
		13: "SETALL",
		14: "DELETEALL",
	}
	FunctionEnumerable_FunctionType_value = map[string]int32{
		"UNKNOWN":   0,
		"MAP":       1,
		"FILTER":    2,
		"FOLD":      3,
		"TAKE":      4,
		"TAKEWHILE": 5,
		"TAKEFIRST": 6,
		"TAKELAST":  7,
		"DROP":      8,
		"DROPWHILE": 9,
		"FOREACH":   10,
		"CONCAT":    11,
		"FLATMAP":   12,
		"SETALL":    13,
		"DELETEALL": 14,
	}
)

func (x FunctionEnumerable_FunctionType) Enum() *FunctionEnumerable_FunctionType {
	p := new(FunctionEnumerable_FunctionType)
	*p = x
	return p
}

func (x FunctionEnumerable_FunctionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionEnumerable_FunctionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operation_proto_enumTypes[0].Descriptor()
}

func (FunctionEnumerable_FunctionType) Type() protoreflect.EnumType {
	return &file_proto_operation_proto_enumTypes[0]
}

func (x FunctionEnumerable_FunctionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionEnumerable_FunctionType.Descriptor instead.
func (FunctionEnumerable_FunctionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{8, 0}
}

type OperationEnumerable_OperationType int32

const (
	OperationEnumerable_UNKNOWN OperationEnumerable_OperationType = 0
	OperationEnumerable_SELECT  OperationEnumerable_OperationType = 1
	OperationEnumerable_SET     OperationEnumerable_OperationType = 2
	OperationEnumerable_DELETE  OperationEnumerable_OperationType = 3
	// create depends on the type of enumerable.
	// for mapping enumerable, the elem is stored under the primitive key
	// for queue enumerable, the elem is stored at the last position
	OperationEnumerable_CREATE OperationEnumerable_OperationType = 4
)

// Enum value maps for OperationEnumerable_OperationType.
var (
	OperationEnumerable_OperationType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SELECT",
		2: "SET",
		3: "DELETE",
		4: "CREATE",
	}
	OperationEnumerable_OperationType_value = map[string]int32{
		"UNKNOWN": 0,
		"SELECT":  1,
		"SET":     2,
		"DELETE":  3,
		"CREATE":  4,
	}
)

func (x OperationEnumerable_OperationType) Enum() *OperationEnumerable_OperationType {
	p := new(OperationEnumerable_OperationType)
	*p = x
	return p
}

func (x OperationEnumerable_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationEnumerable_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operation_proto_enumTypes[1].Descriptor()
}

func (OperationEnumerable_OperationType) Type() protoreflect.EnumType {
	return &file_proto_operation_proto_enumTypes[1]
}

func (x OperationEnumerable_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationEnumerable_OperationType.Descriptor instead.
func (OperationEnumerable_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{9, 0}
}

type FunctionNumeric_Operator int32

const (
	FunctionNumeric_UNKNOWN FunctionNumeric_Operator = 0
	FunctionNumeric_ADD     FunctionNumeric_Operator = 1
	FunctionNumeric_SUB     FunctionNumeric_Operator = 2
	FunctionNumeric_SUBFROM FunctionNumeric_Operator = 3
	FunctionNumeric_MUL     FunctionNumeric_Operator = 4
	FunctionNumeric_DIV     FunctionNumeric_Operator = 5
	FunctionNumeric_LT      FunctionNumeric_Operator = 6
	FunctionNumeric_LTE     FunctionNumeric_Operator = 7
	FunctionNumeric_GT      FunctionNumeric_Operator = 8
	FunctionNumeric_GTE     FunctionNumeric_Operator = 9
	FunctionNumeric_EQ      FunctionNumeric_Operator = 10
	FunctionNumeric_NEQ     FunctionNumeric_Operator = 11
)

// Enum value maps for FunctionNumeric_Operator.
var (
	FunctionNumeric_Operator_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "ADD",
		2:  "SUB",
		3:  "SUBFROM",
		4:  "MUL",
		5:  "DIV",
		6:  "LT",
		7:  "LTE",
		8:  "GT",
		9:  "GTE",
		10: "EQ",
		11: "NEQ",
	}
	FunctionNumeric_Operator_value = map[string]int32{
		"UNKNOWN": 0,
		"ADD":     1,
		"SUB":     2,
		"SUBFROM": 3,
		"MUL":     4,
		"DIV":     5,
		"LT":      6,
		"LTE":     7,
		"GT":      8,
		"GTE":     9,
		"EQ":      10,
		"NEQ":     11,
	}
)

func (x FunctionNumeric_Operator) Enum() *FunctionNumeric_Operator {
	p := new(FunctionNumeric_Operator)
	*p = x
	return p
}

func (x FunctionNumeric_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionNumeric_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operation_proto_enumTypes[2].Descriptor()
}

func (FunctionNumeric_Operator) Type() protoreflect.EnumType {
	return &file_proto_operation_proto_enumTypes[2]
}

func (x FunctionNumeric_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionNumeric_Operator.Descriptor instead.
func (FunctionNumeric_Operator) EnumDescriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{15, 0}
}

type FunctionBoolean_Operator int32

const (
	FunctionBoolean_UNKNOWN FunctionBoolean_Operator = 0
	FunctionBoolean_AND     FunctionBoolean_Operator = 1
	FunctionBoolean_OR      FunctionBoolean_Operator = 2
	FunctionBoolean_XOR     FunctionBoolean_Operator = 3
	FunctionBoolean_NOT     FunctionBoolean_Operator = 4
)

// Enum value maps for FunctionBoolean_Operator.
var (
	FunctionBoolean_Operator_name = map[int32]string{
		0: "UNKNOWN",
		1: "AND",
		2: "OR",
		3: "XOR",
		4: "NOT",
	}
	FunctionBoolean_Operator_value = map[string]int32{
		"UNKNOWN": 0,
		"AND":     1,
		"OR":      2,
		"XOR":     3,
		"NOT":     4,
	}
)

func (x FunctionBoolean_Operator) Enum() *FunctionBoolean_Operator {
	p := new(FunctionBoolean_Operator)
	*p = x
	return p
}

func (x FunctionBoolean_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionBoolean_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operation_proto_enumTypes[3].Descriptor()
}

func (FunctionBoolean_Operator) Type() protoreflect.EnumType {
	return &file_proto_operation_proto_enumTypes[3]
}

func (x FunctionBoolean_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionBoolean_Operator.Descriptor instead.
func (FunctionBoolean_Operator) EnumDescriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{16, 0}
}

type OperationSingle_OperationType int32

const (
	OperationSingle_UNKNOWN OperationSingle_OperationType = 0
	OperationSingle_SELECT  OperationSingle_OperationType = 1
	OperationSingle_SET     OperationSingle_OperationType = 2
	OperationSingle_DELETE  OperationSingle_OperationType = 3
	OperationSingle_CREATE  OperationSingle_OperationType = 4
)

// Enum value maps for OperationSingle_OperationType.
var (
	OperationSingle_OperationType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SELECT",
		2: "SET",
		3: "DELETE",
		4: "CREATE",
	}
	OperationSingle_OperationType_value = map[string]int32{
		"UNKNOWN": 0,
		"SELECT":  1,
		"SET":     2,
		"DELETE":  3,
		"CREATE":  4,
	}
)

func (x OperationSingle_OperationType) Enum() *OperationSingle_OperationType {
	p := new(OperationSingle_OperationType)
	*p = x
	return p
}

func (x OperationSingle_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationSingle_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operation_proto_enumTypes[4].Descriptor()
}

func (OperationSingle_OperationType) Type() protoreflect.EnumType {
	return &file_proto_operation_proto_enumTypes[4]
}

func (x OperationSingle_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationSingle_OperationType.Descriptor instead.
func (OperationSingle_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{19, 0}
}

type OperationAccount_OperationType int32

const (
	OperationAccount_UNKNOWN    OperationAccount_OperationType = 0
	OperationAccount_CREATE     OperationAccount_OperationType = 1
	OperationAccount_DESTRUCT   OperationAccount_OperationType = 2
	OperationAccount_SUBACCOUNT OperationAccount_OperationType = 3
	OperationAccount_LOCK       OperationAccount_OperationType = 4
	OperationAccount_UNLOCK     OperationAccount_OperationType = 5
)

// Enum value maps for OperationAccount_OperationType.
var (
	OperationAccount_OperationType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATE",
		2: "DESTRUCT",
		3: "SUBACCOUNT",
		4: "LOCK",
		5: "UNLOCK",
	}
	OperationAccount_OperationType_value = map[string]int32{
		"UNKNOWN":    0,
		"CREATE":     1,
		"DESTRUCT":   2,
		"SUBACCOUNT": 3,
		"LOCK":       4,
		"UNLOCK":     5,
	}
)

func (x OperationAccount_OperationType) Enum() *OperationAccount_OperationType {
	p := new(OperationAccount_OperationType)
	*p = x
	return p
}

func (x OperationAccount_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationAccount_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operation_proto_enumTypes[5].Descriptor()
}

func (OperationAccount_OperationType) Type() protoreflect.EnumType {
	return &file_proto_operation_proto_enumTypes[5]
}

func (x OperationAccount_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationAccount_OperationType.Descriptor instead.
func (OperationAccount_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{22, 0}
}

type Uint256 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Uint256) Reset() {
	*x = Uint256{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint256) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint256) ProtoMessage() {}

func (x *Uint256) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint256.ProtoReflect.Descriptor instead.
func (*Uint256) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{0}
}

func (x *Uint256) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Int256 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Int256) Reset() {
	*x = Int256{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int256) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int256) ProtoMessage() {}

func (x *Int256) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int256.ProtoReflect.Descriptor instead.
func (*Int256) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{1}
}

func (x *Int256) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Dec256 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Significand *Uint256 `protobuf:"bytes,1,opt,name=significand,proto3" json:"significand,omitempty"`
	Exponent    uint32   `protobuf:"varint,2,opt,name=exponent,proto3" json:"exponent,omitempty"`
}

func (x *Dec256) Reset() {
	*x = Dec256{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dec256) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dec256) ProtoMessage() {}

func (x *Dec256) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dec256.ProtoReflect.Descriptor instead.
func (*Dec256) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{2}
}

func (x *Dec256) GetSignificand() *Uint256 {
	if x != nil {
		return x.Significand
	}
	return nil
}

func (x *Dec256) GetExponent() uint32 {
	if x != nil {
		return x.Exponent
	}
	return 0
}

type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Denom  string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Id     *Uint256 `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"` // explicitly optional, NFT purpose
	Amount *Uint256 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{3}
}

func (x *Asset) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Asset) GetId() *Uint256 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Asset) GetAmount() *Uint256 {
	if x != nil {
		return x.Amount
	}
	return nil
}

type BytesPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BytesPair) Reset() {
	*x = BytesPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesPair) ProtoMessage() {}

func (x *BytesPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesPair.ProtoReflect.Descriptor instead.
func (*BytesPair) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{4}
}

func (x *BytesPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BytesPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// FromKeys :: Enumerable
type FromKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *FromKeys) Reset() {
	*x = FromKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromKeys) ProtoMessage() {}

func (x *FromKeys) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromKeys.ProtoReflect.Descriptor instead.
func (*FromKeys) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{5}
}

func (x *FromKeys) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// FromIterator :: Enumerable
type FromIterator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix    []string `protobuf:"bytes,1,rep,name=prefix,proto3" json:"prefix,omitempty"`
	From      string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Ascending bool     `protobuf:"varint,4,opt,name=ascending,proto3" json:"ascending,omitempty"`
}

func (x *FromIterator) Reset() {
	*x = FromIterator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromIterator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromIterator) ProtoMessage() {}

func (x *FromIterator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromIterator.ProtoReflect.Descriptor instead.
func (*FromIterator) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{6}
}

func (x *FromIterator) GetPrefix() []string {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *FromIterator) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *FromIterator) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *FromIterator) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

type EnumerableFrom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to From:
	//	*EnumerableFrom_Keys
	//	*EnumerableFrom_Iterator
	From isEnumerableFrom_From `protobuf_oneof:"from"`
}

func (x *EnumerableFrom) Reset() {
	*x = EnumerableFrom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumerableFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerableFrom) ProtoMessage() {}

func (x *EnumerableFrom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerableFrom.ProtoReflect.Descriptor instead.
func (*EnumerableFrom) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{7}
}

func (m *EnumerableFrom) GetFrom() isEnumerableFrom_From {
	if m != nil {
		return m.From
	}
	return nil
}

func (x *EnumerableFrom) GetKeys() *FromKeys {
	if x, ok := x.GetFrom().(*EnumerableFrom_Keys); ok {
		return x.Keys
	}
	return nil
}

func (x *EnumerableFrom) GetIterator() *FromIterator {
	if x, ok := x.GetFrom().(*EnumerableFrom_Iterator); ok {
		return x.Iterator
	}
	return nil
}

type isEnumerableFrom_From interface {
	isEnumerableFrom_From()
}

type EnumerableFrom_Keys struct {
	Keys *FromKeys `protobuf:"bytes,1,opt,name=keys,proto3,oneof"`
}

type EnumerableFrom_Iterator struct {
	Iterator *FromIterator `protobuf:"bytes,2,opt,name=iterator,proto3,oneof"`
}

func (*EnumerableFrom_Keys) isEnumerableFrom_From() {}

func (*EnumerableFrom_Iterator) isEnumerableFrom_From() {}

// FunctionHighorder takes a single unary function and lifts it to list level
// or processes the enumeration without a base function
// FunctionEnumerable can be used both on list element and enumeration stream
type FunctionEnumerable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     FunctionEnumerable_FunctionType `protobuf:"varint,1,opt,name=type,proto3,enum=dbci.operation.FunctionEnumerable_FunctionType" json:"type,omitempty"`
	Function *FunctionSingle                 `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *FunctionEnumerable) Reset() {
	*x = FunctionEnumerable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionEnumerable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionEnumerable) ProtoMessage() {}

func (x *FunctionEnumerable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionEnumerable.ProtoReflect.Descriptor instead.
func (*FunctionEnumerable) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{8}
}

func (x *FunctionEnumerable) GetType() FunctionEnumerable_FunctionType {
	if x != nil {
		return x.Type
	}
	return FunctionEnumerable_UNKNOWN
}

func (x *FunctionEnumerable) GetFunction() *FunctionSingle {
	if x != nil {
		return x.Function
	}
	return nil
}

type OperationEnumerable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     OperationEnumerable_OperationType `protobuf:"varint,1,opt,name=type,proto3,enum=dbci.operation.OperationEnumerable_OperationType" json:"type,omitempty"`
	From     *EnumerableFrom                   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Function []*FunctionEnumerable             `protobuf:"bytes,3,rep,name=function,proto3" json:"function,omitempty"`
}

func (x *OperationEnumerable) Reset() {
	*x = OperationEnumerable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationEnumerable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationEnumerable) ProtoMessage() {}

func (x *OperationEnumerable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationEnumerable.ProtoReflect.Descriptor instead.
func (*OperationEnumerable) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{9}
}

func (x *OperationEnumerable) GetType() OperationEnumerable_OperationType {
	if x != nil {
		return x.Type
	}
	return OperationEnumerable_UNKNOWN
}

func (x *OperationEnumerable) GetFrom() *EnumerableFrom {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *OperationEnumerable) GetFunction() []*FunctionEnumerable {
	if x != nil {
		return x.Function
	}
	return nil
}

type QueryEnumerableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ops []*OperationEnumerable `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
}

func (x *QueryEnumerableRequest) Reset() {
	*x = QueryEnumerableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEnumerableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEnumerableRequest) ProtoMessage() {}

func (x *QueryEnumerableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEnumerableRequest.ProtoReflect.Descriptor instead.
func (*QueryEnumerableRequest) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{10}
}

func (x *QueryEnumerableRequest) GetOps() []*OperationEnumerable {
	if x != nil {
		return x.Ops
	}
	return nil
}

type QueryEnumerableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*BytesPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *QueryEnumerableResponse) Reset() {
	*x = QueryEnumerableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEnumerableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEnumerableResponse) ProtoMessage() {}

func (x *QueryEnumerableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEnumerableResponse.ProtoReflect.Descriptor instead.
func (*QueryEnumerableResponse) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{11}
}

func (x *QueryEnumerableResponse) GetPairs() []*BytesPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

// FromKey :: Single
type FromKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *FromKey) Reset() {
	*x = FromKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromKey) ProtoMessage() {}

func (x *FromKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromKey.ProtoReflect.Descriptor instead.
func (*FromKey) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{12}
}

func (x *FromKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FromConstant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FromConstant) Reset() {
	*x = FromConstant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromConstant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromConstant) ProtoMessage() {}

func (x *FromConstant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromConstant.ProtoReflect.Descriptor instead.
func (*FromConstant) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{13}
}

func (x *FromConstant) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FromConstant) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SingleFrom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to From:
	//	*SingleFrom_Key
	From isSingleFrom_From `protobuf_oneof:"from"`
}

func (x *SingleFrom) Reset() {
	*x = SingleFrom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleFrom) ProtoMessage() {}

func (x *SingleFrom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleFrom.ProtoReflect.Descriptor instead.
func (*SingleFrom) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{14}
}

func (m *SingleFrom) GetFrom() isSingleFrom_From {
	if m != nil {
		return m.From
	}
	return nil
}

func (x *SingleFrom) GetKey() *FromKey {
	if x, ok := x.GetFrom().(*SingleFrom_Key); ok {
		return x.Key
	}
	return nil
}

type isSingleFrom_From interface {
	isSingleFrom_From()
}

type SingleFrom_Key struct {
	Key *FromKey `protobuf:"bytes,1,opt,name=key,proto3,oneof"`
}

func (*SingleFrom_Key) isSingleFrom_From() {}

// FunctionNumeric :: Numeric -> Numeric
type FunctionNumeric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator FunctionNumeric_Operator `protobuf:"varint,1,opt,name=operator,proto3,enum=dbci.operation.FunctionNumeric_Operator" json:"operator,omitempty"`
	// Types that are assignable to Operand:
	//	*FunctionNumeric_Uint64Operand
	//	*FunctionNumeric_Int64Operand
	//	*FunctionNumeric_Uint256Operand
	//	*FunctionNumeric_Int256Operand
	Operand isFunctionNumeric_Operand `protobuf_oneof:"operand"`
}

func (x *FunctionNumeric) Reset() {
	*x = FunctionNumeric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionNumeric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionNumeric) ProtoMessage() {}

func (x *FunctionNumeric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionNumeric.ProtoReflect.Descriptor instead.
func (*FunctionNumeric) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{15}
}

func (x *FunctionNumeric) GetOperator() FunctionNumeric_Operator {
	if x != nil {
		return x.Operator
	}
	return FunctionNumeric_UNKNOWN
}

func (m *FunctionNumeric) GetOperand() isFunctionNumeric_Operand {
	if m != nil {
		return m.Operand
	}
	return nil
}

func (x *FunctionNumeric) GetUint64Operand() uint64 {
	if x, ok := x.GetOperand().(*FunctionNumeric_Uint64Operand); ok {
		return x.Uint64Operand
	}
	return 0
}

func (x *FunctionNumeric) GetInt64Operand() int64 {
	if x, ok := x.GetOperand().(*FunctionNumeric_Int64Operand); ok {
		return x.Int64Operand
	}
	return 0
}

func (x *FunctionNumeric) GetUint256Operand() *Uint256 {
	if x, ok := x.GetOperand().(*FunctionNumeric_Uint256Operand); ok {
		return x.Uint256Operand
	}
	return nil
}

func (x *FunctionNumeric) GetInt256Operand() *Int256 {
	if x, ok := x.GetOperand().(*FunctionNumeric_Int256Operand); ok {
		return x.Int256Operand
	}
	return nil
}

type isFunctionNumeric_Operand interface {
	isFunctionNumeric_Operand()
}

type FunctionNumeric_Uint64Operand struct {
	Uint64Operand uint64 `protobuf:"varint,2,opt,name=uint64Operand,proto3,oneof"`
}

type FunctionNumeric_Int64Operand struct {
	Int64Operand int64 `protobuf:"varint,3,opt,name=int64Operand,proto3,oneof"`
}

type FunctionNumeric_Uint256Operand struct {
	Uint256Operand *Uint256 `protobuf:"bytes,4,opt,name=Uint256Operand,proto3,oneof"`
}

type FunctionNumeric_Int256Operand struct {
	Int256Operand *Int256 `protobuf:"bytes,5,opt,name=Int256Operand,proto3,oneof"`
}

func (*FunctionNumeric_Uint64Operand) isFunctionNumeric_Operand() {}

func (*FunctionNumeric_Int64Operand) isFunctionNumeric_Operand() {}

func (*FunctionNumeric_Uint256Operand) isFunctionNumeric_Operand() {}

func (*FunctionNumeric_Int256Operand) isFunctionNumeric_Operand() {}

type FunctionBoolean struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator FunctionBoolean_Operator `protobuf:"varint,1,opt,name=operator,proto3,enum=dbci.operation.FunctionBoolean_Operator" json:"operator,omitempty"`
	Function []*FunctionSingle        `protobuf:"bytes,2,rep,name=function,proto3" json:"function,omitempty"`
}

func (x *FunctionBoolean) Reset() {
	*x = FunctionBoolean{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionBoolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionBoolean) ProtoMessage() {}

func (x *FunctionBoolean) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionBoolean.ProtoReflect.Descriptor instead.
func (*FunctionBoolean) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{16}
}

func (x *FunctionBoolean) GetOperator() FunctionBoolean_Operator {
	if x != nil {
		return x.Operator
	}
	return FunctionBoolean_UNKNOWN
}

func (x *FunctionBoolean) GetFunction() []*FunctionSingle {
	if x != nil {
		return x.Function
	}
	return nil
}

// FunctionSelectField ::
// a, b proto.Message => a -> b
// This is equal with FieldDescriptor, I just couldnt found how to import it properly
type FunctionSelectField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldNumber int32 `protobuf:"varint,1,opt,name=fieldNumber,proto3" json:"fieldNumber,omitempty"`
	FieldType   int32 `protobuf:"varint,2,opt,name=fieldType,proto3" json:"fieldType,omitempty"` // int8, consider switching to enum
}

func (x *FunctionSelectField) Reset() {
	*x = FunctionSelectField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionSelectField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionSelectField) ProtoMessage() {}

func (x *FunctionSelectField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionSelectField.ProtoReflect.Descriptor instead.
func (*FunctionSelectField) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{17}
}

func (x *FunctionSelectField) GetFieldNumber() int32 {
	if x != nil {
		return x.FieldNumber
	}
	return 0
}

func (x *FunctionSelectField) GetFieldType() int32 {
	if x != nil {
		return x.FieldType
	}
	return 0
}

type FunctionSingle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Fn:
	//	*FunctionSingle_Numeric
	//	*FunctionSingle_SelectField
	//	*FunctionSingle_Boolean
	Fn isFunctionSingle_Fn `protobuf_oneof:"fn"`
}

func (x *FunctionSingle) Reset() {
	*x = FunctionSingle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionSingle) ProtoMessage() {}

func (x *FunctionSingle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionSingle.ProtoReflect.Descriptor instead.
func (*FunctionSingle) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{18}
}

func (m *FunctionSingle) GetFn() isFunctionSingle_Fn {
	if m != nil {
		return m.Fn
	}
	return nil
}

func (x *FunctionSingle) GetNumeric() *FunctionNumeric {
	if x, ok := x.GetFn().(*FunctionSingle_Numeric); ok {
		return x.Numeric
	}
	return nil
}

func (x *FunctionSingle) GetSelectField() *FunctionSelectField {
	if x, ok := x.GetFn().(*FunctionSingle_SelectField); ok {
		return x.SelectField
	}
	return nil
}

func (x *FunctionSingle) GetBoolean() *FunctionBoolean {
	if x, ok := x.GetFn().(*FunctionSingle_Boolean); ok {
		return x.Boolean
	}
	return nil
}

type isFunctionSingle_Fn interface {
	isFunctionSingle_Fn()
}

type FunctionSingle_Numeric struct {
	Numeric *FunctionNumeric `protobuf:"bytes,1,opt,name=numeric,proto3,oneof"` // Numeric -> Numeric
}

type FunctionSingle_SelectField struct {
	SelectField *FunctionSelectField `protobuf:"bytes,2,opt,name=selectField,proto3,oneof"`
}

type FunctionSingle_Boolean struct {
	Boolean *FunctionBoolean `protobuf:"bytes,3,opt,name=boolean,proto3,oneof"` // FunctionSplit split = 4;
}

func (*FunctionSingle_Numeric) isFunctionSingle_Fn() {}

func (*FunctionSingle_SelectField) isFunctionSingle_Fn() {}

func (*FunctionSingle_Boolean) isFunctionSingle_Fn() {}

type OperationSingle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      OperationSingle_OperationType `protobuf:"varint,1,opt,name=type,proto3,enum=dbci.operation.OperationSingle_OperationType" json:"type,omitempty"`
	Account   string                        `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	From      *SingleFrom                   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Functions []*FunctionSingle             `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
}

func (x *OperationSingle) Reset() {
	*x = OperationSingle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationSingle) ProtoMessage() {}

func (x *OperationSingle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationSingle.ProtoReflect.Descriptor instead.
func (*OperationSingle) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{19}
}

func (x *OperationSingle) GetType() OperationSingle_OperationType {
	if x != nil {
		return x.Type
	}
	return OperationSingle_UNKNOWN
}

func (x *OperationSingle) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *OperationSingle) GetFrom() *SingleFrom {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *OperationSingle) GetFunctions() []*FunctionSingle {
	if x != nil {
		return x.Functions
	}
	return nil
}

type QuerySingleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ops []*OperationSingle `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
}

func (x *QuerySingleRequest) Reset() {
	*x = QuerySingleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuerySingleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySingleRequest) ProtoMessage() {}

func (x *QuerySingleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySingleRequest.ProtoReflect.Descriptor instead.
func (*QuerySingleRequest) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{20}
}

func (x *QuerySingleRequest) GetOps() []*OperationSingle {
	if x != nil {
		return x.Ops
	}
	return nil
}

type QuerySingleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair *BytesPair `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *QuerySingleResponse) Reset() {
	*x = QuerySingleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuerySingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySingleResponse) ProtoMessage() {}

func (x *QuerySingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySingleResponse.ProtoReflect.Descriptor instead.
func (*QuerySingleResponse) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{21}
}

func (x *QuerySingleResponse) GetPair() *BytesPair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type OperationAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type OperationAccount_OperationType `protobuf:"varint,1,opt,name=type,proto3,enum=dbci.operation.OperationAccount_OperationType" json:"type,omitempty"`
}

func (x *OperationAccount) Reset() {
	*x = OperationAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationAccount) ProtoMessage() {}

func (x *OperationAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationAccount.ProtoReflect.Descriptor instead.
func (*OperationAccount) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{22}
}

func (x *OperationAccount) GetType() OperationAccount_OperationType {
	if x != nil {
		return x.Type
	}
	return OperationAccount_UNKNOWN
}

var File_proto_operation_proto protoreflect.FileDescriptor

var file_proto_operation_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1d, 0x0a, 0x07, 0x55, 0x69, 0x6e, 0x74, 0x32,
	0x35, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1c, 0x0a, 0x06, 0x49, 0x6e, 0x74, 0x32, 0x35, 0x36,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x5f, 0x0a, 0x06, 0x44, 0x65, 0x63, 0x32, 0x35, 0x36, 0x12, 0x39,
	0x0a, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x52, 0x0b, 0x73, 0x69,
	0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x65, 0x78, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x2c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x09, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x1e, 0x0a, 0x08, 0x46, 0x72, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x22, 0x68, 0x0a, 0x0c, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x45,
	0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x2e, 0x0a,
	0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x62,
	0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x72, 0x6f,
	0x6d, 0x4b, 0x65, 0x79, 0x73, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x3a, 0x0a,
	0x08, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x08, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x22, 0xe2, 0x02, 0x0a, 0x12, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e,
	0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a,
	0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52,
	0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xca, 0x01, 0x0a, 0x0c, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x41, 0x50, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x46, 0x4f, 0x4c, 0x44, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x41, 0x4b, 0x45, 0x10, 0x04,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x41, 0x4b, 0x45, 0x57, 0x48, 0x49, 0x4c, 0x45, 0x10, 0x05, 0x12,
	0x0d, 0x0a, 0x09, 0x54, 0x41, 0x4b, 0x45, 0x46, 0x49, 0x52, 0x53, 0x54, 0x10, 0x06, 0x12, 0x0c,
	0x0a, 0x08, 0x54, 0x41, 0x4b, 0x45, 0x4c, 0x41, 0x53, 0x54, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x52, 0x4f, 0x50, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x52, 0x4f, 0x50, 0x57, 0x48,
	0x49, 0x4c, 0x45, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4f, 0x52, 0x45, 0x41, 0x43, 0x48,
	0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4e, 0x43, 0x41, 0x54, 0x10, 0x0b, 0x12, 0x0b,
	0x0a, 0x07, 0x46, 0x4c, 0x41, 0x54, 0x4d, 0x41, 0x50, 0x10, 0x0c, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x45, 0x54, 0x41, 0x4c, 0x4c, 0x10, 0x0d, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x41, 0x4c, 0x4c, 0x10, 0x0e, 0x22, 0x9b, 0x02, 0x0a, 0x13, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x45,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x64,
	0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c,
	0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x3e, 0x0a, 0x08, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x62,
	0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x0d, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x4c, 0x45, 0x43,
	0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x10, 0x04, 0x22, 0x4f, 0x0a, 0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x75,
	0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35,
	0x0a, 0x03, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x62,
	0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x03, 0x6f, 0x70, 0x73, 0x22, 0x4a, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e,
	0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72,
	0x73, 0x22, 0x1b, 0x0a, 0x07, 0x46, 0x72, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x36,
	0x0a, 0x0c, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x41, 0x0a, 0x0a, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x2b, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x42, 0x06, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0xb0, 0x03, 0x0a, 0x0f, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x44, 0x0a,
	0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x28, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0d, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0d, 0x75, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0c, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e,
	0x64, 0x12, 0x41, 0x0a, 0x0e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x63, 0x69,
	0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32,
	0x35, 0x36, 0x48, 0x00, 0x52, 0x0e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x12, 0x3e, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x62,
	0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x74,
	0x32, 0x35, 0x36, 0x48, 0x00, 0x52, 0x0d, 0x49, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x22, 0x7b, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x42, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x42, 0x46, 0x52, 0x4f, 0x4d, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03,
	0x4d, 0x55, 0x4c, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x56, 0x10, 0x05, 0x12, 0x06,
	0x0a, 0x02, 0x4c, 0x54, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10, 0x07, 0x12,
	0x06, 0x0a, 0x02, 0x47, 0x54, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x45, 0x10, 0x09,
	0x12, 0x06, 0x0a, 0x02, 0x45, 0x51, 0x10, 0x0a, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x51, 0x10,
	0x0b, 0x42, 0x09, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x22, 0xcf, 0x01, 0x0a,
	0x0f, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x12, 0x44, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x28, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x6f, 0x6c,
	0x65, 0x61, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x3a, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x4e, 0x44, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03,
	0x58, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x4f, 0x54, 0x10, 0x04, 0x22, 0x55,
	0x0a, 0x13, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0xd9, 0x01, 0x0a, 0x0e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x65,
	0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x62, 0x63, 0x69,
	0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x75,
	0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x47, 0x0a, 0x0b, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x62, 0x63,
	0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x48,
	0x00, 0x52, 0x0b, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3b,
	0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x42, 0x04, 0x0a, 0x02, 0x66,
	0x6e, 0x22, 0xa7, 0x02, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x3c, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x49, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45,
	0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x04, 0x22, 0x47, 0x0a, 0x12, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x03, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52,
	0x03, 0x6f, 0x70, 0x73, 0x22, 0x44, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x70,
	0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x62, 0x63, 0x69,
	0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x42, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e,
	0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x5c, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x44, 0x45, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53,
	0x55, 0x42, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x4f, 0x43, 0x4b, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4c, 0x4f, 0x43, 0x4b, 0x10,
	0x05, 0x32, 0x7c, 0x0a, 0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x0f, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x26,
	0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x75,
	0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x6c, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x12, 0x22, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x63, 0x6f, 0x6e,
	0x63, 0x61, 0x74, 0x2f, 0x64, 0x62, 0x63, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_operation_proto_rawDescOnce sync.Once
	file_proto_operation_proto_rawDescData = file_proto_operation_proto_rawDesc
)

func file_proto_operation_proto_rawDescGZIP() []byte {
	file_proto_operation_proto_rawDescOnce.Do(func() {
		file_proto_operation_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_operation_proto_rawDescData)
	})
	return file_proto_operation_proto_rawDescData
}

var file_proto_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_operation_proto_goTypes = []interface{}{
	(FunctionEnumerable_FunctionType)(0),   // 0: dbci.operation.FunctionEnumerable.FunctionType
	(OperationEnumerable_OperationType)(0), // 1: dbci.operation.OperationEnumerable.OperationType
	(FunctionNumeric_Operator)(0),          // 2: dbci.operation.FunctionNumeric.Operator
	(FunctionBoolean_Operator)(0),          // 3: dbci.operation.FunctionBoolean.Operator
	(OperationSingle_OperationType)(0),     // 4: dbci.operation.OperationSingle.OperationType
	(OperationAccount_OperationType)(0),    // 5: dbci.operation.OperationAccount.OperationType
	(*Uint256)(nil),                        // 6: dbci.operation.Uint256
	(*Int256)(nil),                         // 7: dbci.operation.Int256
	(*Dec256)(nil),                         // 8: dbci.operation.Dec256
	(*Asset)(nil),                          // 9: dbci.operation.Asset
	(*BytesPair)(nil),                      // 10: dbci.operation.BytesPair
	(*FromKeys)(nil),                       // 11: dbci.operation.FromKeys
	(*FromIterator)(nil),                   // 12: dbci.operation.FromIterator
	(*EnumerableFrom)(nil),                 // 13: dbci.operation.EnumerableFrom
	(*FunctionEnumerable)(nil),             // 14: dbci.operation.FunctionEnumerable
	(*OperationEnumerable)(nil),            // 15: dbci.operation.OperationEnumerable
	(*QueryEnumerableRequest)(nil),         // 16: dbci.operation.QueryEnumerableRequest
	(*QueryEnumerableResponse)(nil),        // 17: dbci.operation.QueryEnumerableResponse
	(*FromKey)(nil),                        // 18: dbci.operation.FromKey
	(*FromConstant)(nil),                   // 19: dbci.operation.FromConstant
	(*SingleFrom)(nil),                     // 20: dbci.operation.SingleFrom
	(*FunctionNumeric)(nil),                // 21: dbci.operation.FunctionNumeric
	(*FunctionBoolean)(nil),                // 22: dbci.operation.FunctionBoolean
	(*FunctionSelectField)(nil),            // 23: dbci.operation.FunctionSelectField
	(*FunctionSingle)(nil),                 // 24: dbci.operation.FunctionSingle
	(*OperationSingle)(nil),                // 25: dbci.operation.OperationSingle
	(*QuerySingleRequest)(nil),             // 26: dbci.operation.QuerySingleRequest
	(*QuerySingleResponse)(nil),            // 27: dbci.operation.QuerySingleResponse
	(*OperationAccount)(nil),               // 28: dbci.operation.OperationAccount
}
var file_proto_operation_proto_depIdxs = []int32{
	6,  // 0: dbci.operation.Dec256.significand:type_name -> dbci.operation.Uint256
	6,  // 1: dbci.operation.Asset.id:type_name -> dbci.operation.Uint256
	6,  // 2: dbci.operation.Asset.amount:type_name -> dbci.operation.Uint256
	11, // 3: dbci.operation.EnumerableFrom.keys:type_name -> dbci.operation.FromKeys
	12, // 4: dbci.operation.EnumerableFrom.iterator:type_name -> dbci.operation.FromIterator
	0,  // 5: dbci.operation.FunctionEnumerable.type:type_name -> dbci.operation.FunctionEnumerable.FunctionType
	24, // 6: dbci.operation.FunctionEnumerable.function:type_name -> dbci.operation.FunctionSingle
	1,  // 7: dbci.operation.OperationEnumerable.type:type_name -> dbci.operation.OperationEnumerable.OperationType
	13, // 8: dbci.operation.OperationEnumerable.from:type_name -> dbci.operation.EnumerableFrom
	14, // 9: dbci.operation.OperationEnumerable.function:type_name -> dbci.operation.FunctionEnumerable
	15, // 10: dbci.operation.QueryEnumerableRequest.ops:type_name -> dbci.operation.OperationEnumerable
	10, // 11: dbci.operation.QueryEnumerableResponse.pairs:type_name -> dbci.operation.BytesPair
	18, // 12: dbci.operation.SingleFrom.key:type_name -> dbci.operation.FromKey
	2,  // 13: dbci.operation.FunctionNumeric.operator:type_name -> dbci.operation.FunctionNumeric.Operator
	6,  // 14: dbci.operation.FunctionNumeric.Uint256Operand:type_name -> dbci.operation.Uint256
	7,  // 15: dbci.operation.FunctionNumeric.Int256Operand:type_name -> dbci.operation.Int256
	3,  // 16: dbci.operation.FunctionBoolean.operator:type_name -> dbci.operation.FunctionBoolean.Operator
	24, // 17: dbci.operation.FunctionBoolean.function:type_name -> dbci.operation.FunctionSingle
	21, // 18: dbci.operation.FunctionSingle.numeric:type_name -> dbci.operation.FunctionNumeric
	23, // 19: dbci.operation.FunctionSingle.selectField:type_name -> dbci.operation.FunctionSelectField
	22, // 20: dbci.operation.FunctionSingle.boolean:type_name -> dbci.operation.FunctionBoolean
	4,  // 21: dbci.operation.OperationSingle.type:type_name -> dbci.operation.OperationSingle.OperationType
	20, // 22: dbci.operation.OperationSingle.from:type_name -> dbci.operation.SingleFrom
	24, // 23: dbci.operation.OperationSingle.functions:type_name -> dbci.operation.FunctionSingle
	25, // 24: dbci.operation.QuerySingleRequest.ops:type_name -> dbci.operation.OperationSingle
	10, // 25: dbci.operation.QuerySingleResponse.pair:type_name -> dbci.operation.BytesPair
	5,  // 26: dbci.operation.OperationAccount.type:type_name -> dbci.operation.OperationAccount.OperationType
	16, // 27: dbci.operation.QueryEnumerableService.QueryEnumerable:input_type -> dbci.operation.QueryEnumerableRequest
	26, // 28: dbci.operation.QuerySingleService.QuerySingle:input_type -> dbci.operation.QuerySingleRequest
	17, // 29: dbci.operation.QueryEnumerableService.QueryEnumerable:output_type -> dbci.operation.QueryEnumerableResponse
	27, // 30: dbci.operation.QuerySingleService.QuerySingle:output_type -> dbci.operation.QuerySingleResponse
	29, // [29:31] is the sub-list for method output_type
	27, // [27:29] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_operation_proto_init() }
func file_proto_operation_proto_init() {
	if File_proto_operation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_operation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uint256); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int256); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dec256); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromIterator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumerableFrom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionEnumerable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationEnumerable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEnumerableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEnumerableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromConstant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleFrom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionNumeric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionBoolean); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionSelectField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionSingle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationSingle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuerySingleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuerySingleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_operation_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_proto_operation_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*EnumerableFrom_Keys)(nil),
		(*EnumerableFrom_Iterator)(nil),
	}
	file_proto_operation_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*SingleFrom_Key)(nil),
	}
	file_proto_operation_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*FunctionNumeric_Uint64Operand)(nil),
		(*FunctionNumeric_Int64Operand)(nil),
		(*FunctionNumeric_Uint256Operand)(nil),
		(*FunctionNumeric_Int256Operand)(nil),
	}
	file_proto_operation_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*FunctionSingle_Numeric)(nil),
		(*FunctionSingle_SelectField)(nil),
		(*FunctionSingle_Boolean)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_operation_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_operation_proto_goTypes,
		DependencyIndexes: file_proto_operation_proto_depIdxs,
		EnumInfos:         file_proto_operation_proto_enumTypes,
		MessageInfos:      file_proto_operation_proto_msgTypes,
	}.Build()
	File_proto_operation_proto = out.File
	file_proto_operation_proto_rawDesc = nil
	file_proto_operation_proto_goTypes = nil
	file_proto_operation_proto_depIdxs = nil
}
