// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/operation.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionNumeric_Operator int32

const (
	FunctionNumeric_UNKNOWN FunctionNumeric_Operator = 0
	FunctionNumeric_ADD     FunctionNumeric_Operator = 1
	FunctionNumeric_SUB     FunctionNumeric_Operator = 2
	FunctionNumeric_MUL     FunctionNumeric_Operator = 3
	FunctionNumeric_DIV     FunctionNumeric_Operator = 4
	FunctionNumeric_LT      FunctionNumeric_Operator = 5
	FunctionNumeric_LTE     FunctionNumeric_Operator = 6
	FunctionNumeric_GT      FunctionNumeric_Operator = 7
	FunctionNumeric_GTE     FunctionNumeric_Operator = 8
	FunctionNumeric_EQ      FunctionNumeric_Operator = 9
	FunctionNumeric_NEQ     FunctionNumeric_Operator = 10
)

// Enum value maps for FunctionNumeric_Operator.
var (
	FunctionNumeric_Operator_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "ADD",
		2:  "SUB",
		3:  "MUL",
		4:  "DIV",
		5:  "LT",
		6:  "LTE",
		7:  "GT",
		8:  "GTE",
		9:  "EQ",
		10: "NEQ",
	}
	FunctionNumeric_Operator_value = map[string]int32{
		"UNKNOWN": 0,
		"ADD":     1,
		"SUB":     2,
		"MUL":     3,
		"DIV":     4,
		"LT":      5,
		"LTE":     6,
		"GT":      7,
		"GTE":     8,
		"EQ":      9,
		"NEQ":     10,
	}
)

func (x FunctionNumeric_Operator) Enum() *FunctionNumeric_Operator {
	p := new(FunctionNumeric_Operator)
	*p = x
	return p
}

func (x FunctionNumeric_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionNumeric_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operation_proto_enumTypes[0].Descriptor()
}

func (FunctionNumeric_Operator) Type() protoreflect.EnumType {
	return &file_proto_operation_proto_enumTypes[0]
}

func (x FunctionNumeric_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionNumeric_Operator.Descriptor instead.
func (FunctionNumeric_Operator) EnumDescriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{3, 0}
}

type FunctionEnumerable_FunctionType int32

const (
	FunctionEnumerable_UNKNOWN   FunctionEnumerable_FunctionType = 0
	FunctionEnumerable_MAP       FunctionEnumerable_FunctionType = 1 // Lift T -> U
	FunctionEnumerable_FILTER    FunctionEnumerable_FunctionType = 2 // Lift T -> bool
	FunctionEnumerable_FOLD      FunctionEnumerable_FunctionType = 3 // Lift [T] -> U
	FunctionEnumerable_TAKE      FunctionEnumerable_FunctionType = 4 // Nullary
	FunctionEnumerable_TAKEWHILE FunctionEnumerable_FunctionType = 5 // Lift T -> bool
	FunctionEnumerable_DROP      FunctionEnumerable_FunctionType = 6
	FunctionEnumerable_DROPWHILE FunctionEnumerable_FunctionType = 7
)

// Enum value maps for FunctionEnumerable_FunctionType.
var (
	FunctionEnumerable_FunctionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MAP",
		2: "FILTER",
		3: "FOLD",
		4: "TAKE",
		5: "TAKEWHILE",
		6: "DROP",
		7: "DROPWHILE",
	}
	FunctionEnumerable_FunctionType_value = map[string]int32{
		"UNKNOWN":   0,
		"MAP":       1,
		"FILTER":    2,
		"FOLD":      3,
		"TAKE":      4,
		"TAKEWHILE": 5,
		"DROP":      6,
		"DROPWHILE": 7,
	}
)

func (x FunctionEnumerable_FunctionType) Enum() *FunctionEnumerable_FunctionType {
	p := new(FunctionEnumerable_FunctionType)
	*p = x
	return p
}

func (x FunctionEnumerable_FunctionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionEnumerable_FunctionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operation_proto_enumTypes[1].Descriptor()
}

func (FunctionEnumerable_FunctionType) Type() protoreflect.EnumType {
	return &file_proto_operation_proto_enumTypes[1]
}

func (x FunctionEnumerable_FunctionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionEnumerable_FunctionType.Descriptor instead.
func (FunctionEnumerable_FunctionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{6, 0}
}

type Uint256 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A uint64 `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B uint64 `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	C uint64 `protobuf:"fixed64,3,opt,name=c,proto3" json:"c,omitempty"`
	D uint64 `protobuf:"fixed64,4,opt,name=d,proto3" json:"d,omitempty"`
}

func (x *Uint256) Reset() {
	*x = Uint256{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint256) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint256) ProtoMessage() {}

func (x *Uint256) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint256.ProtoReflect.Descriptor instead.
func (*Uint256) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{0}
}

func (x *Uint256) GetA() uint64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Uint256) GetB() uint64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Uint256) GetC() uint64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *Uint256) GetD() uint64 {
	if x != nil {
		return x.D
	}
	return 0
}

type Int256 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A uint64 `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B uint64 `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	C uint64 `protobuf:"fixed64,3,opt,name=c,proto3" json:"c,omitempty"`
	D uint64 `protobuf:"fixed64,4,opt,name=d,proto3" json:"d,omitempty"`
}

func (x *Int256) Reset() {
	*x = Int256{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int256) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int256) ProtoMessage() {}

func (x *Int256) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int256.ProtoReflect.Descriptor instead.
func (*Int256) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{1}
}

func (x *Int256) GetA() uint64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Int256) GetB() uint64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Int256) GetC() uint64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *Int256) GetD() uint64 {
	if x != nil {
		return x.D
	}
	return 0
}

type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Denom  string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Id     *Uint256 `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"` // explicitly optional, NFT purpose
	Amount *Uint256 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{2}
}

func (x *Asset) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Asset) GetId() *Uint256 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Asset) GetAmount() *Uint256 {
	if x != nil {
		return x.Amount
	}
	return nil
}

// FunctionNumeric :: Numeric -> Numeric
type FunctionNumeric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator FunctionNumeric_Operator `protobuf:"varint,1,opt,name=operator,proto3,enum=dbci.operation.FunctionNumeric_Operator" json:"operator,omitempty"`
	// Types that are assignable to Operand:
	//	*FunctionNumeric_Uint64Operand
	//	*FunctionNumeric_Int64Operand
	//	*FunctionNumeric_Uint256Operand
	//	*FunctionNumeric_Int256Operand
	Operand isFunctionNumeric_Operand `protobuf_oneof:"operand"`
}

func (x *FunctionNumeric) Reset() {
	*x = FunctionNumeric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionNumeric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionNumeric) ProtoMessage() {}

func (x *FunctionNumeric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionNumeric.ProtoReflect.Descriptor instead.
func (*FunctionNumeric) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionNumeric) GetOperator() FunctionNumeric_Operator {
	if x != nil {
		return x.Operator
	}
	return FunctionNumeric_UNKNOWN
}

func (m *FunctionNumeric) GetOperand() isFunctionNumeric_Operand {
	if m != nil {
		return m.Operand
	}
	return nil
}

func (x *FunctionNumeric) GetUint64Operand() uint64 {
	if x, ok := x.GetOperand().(*FunctionNumeric_Uint64Operand); ok {
		return x.Uint64Operand
	}
	return 0
}

func (x *FunctionNumeric) GetInt64Operand() int64 {
	if x, ok := x.GetOperand().(*FunctionNumeric_Int64Operand); ok {
		return x.Int64Operand
	}
	return 0
}

func (x *FunctionNumeric) GetUint256Operand() *Uint256 {
	if x, ok := x.GetOperand().(*FunctionNumeric_Uint256Operand); ok {
		return x.Uint256Operand
	}
	return nil
}

func (x *FunctionNumeric) GetInt256Operand() *Int256 {
	if x, ok := x.GetOperand().(*FunctionNumeric_Int256Operand); ok {
		return x.Int256Operand
	}
	return nil
}

type isFunctionNumeric_Operand interface {
	isFunctionNumeric_Operand()
}

type FunctionNumeric_Uint64Operand struct {
	Uint64Operand uint64 `protobuf:"varint,2,opt,name=uint64Operand,proto3,oneof"`
}

type FunctionNumeric_Int64Operand struct {
	Int64Operand int64 `protobuf:"varint,3,opt,name=int64Operand,proto3,oneof"`
}

type FunctionNumeric_Uint256Operand struct {
	Uint256Operand *Uint256 `protobuf:"bytes,4,opt,name=Uint256Operand,proto3,oneof"`
}

type FunctionNumeric_Int256Operand struct {
	Int256Operand *Int256 `protobuf:"bytes,5,opt,name=Int256Operand,proto3,oneof"`
}

func (*FunctionNumeric_Uint64Operand) isFunctionNumeric_Operand() {}

func (*FunctionNumeric_Int64Operand) isFunctionNumeric_Operand() {}

func (*FunctionNumeric_Uint256Operand) isFunctionNumeric_Operand() {}

func (*FunctionNumeric_Int256Operand) isFunctionNumeric_Operand() {}

// FunctionSelectField ::
// a, b proto.Message => a -> b
// This is equal with FieldDescriptor, I just couldnt found how to import it properly
type FunctionSelectField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldNumber int32 `protobuf:"varint,1,opt,name=fieldNumber,proto3" json:"fieldNumber,omitempty"`
	FieldType   int32 `protobuf:"varint,2,opt,name=fieldType,proto3" json:"fieldType,omitempty"` // int8, consider switching to enum
}

func (x *FunctionSelectField) Reset() {
	*x = FunctionSelectField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionSelectField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionSelectField) ProtoMessage() {}

func (x *FunctionSelectField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionSelectField.ProtoReflect.Descriptor instead.
func (*FunctionSelectField) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionSelectField) GetFieldNumber() int32 {
	if x != nil {
		return x.FieldNumber
	}
	return 0
}

func (x *FunctionSelectField) GetFieldType() int32 {
	if x != nil {
		return x.FieldType
	}
	return 0
}

type FunctionSequence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fn []*Function `protobuf:"bytes,1,rep,name=fn,proto3" json:"fn,omitempty"`
}

func (x *FunctionSequence) Reset() {
	*x = FunctionSequence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionSequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionSequence) ProtoMessage() {}

func (x *FunctionSequence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionSequence.ProtoReflect.Descriptor instead.
func (*FunctionSequence) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionSequence) GetFn() []*Function {
	if x != nil {
		return x.Fn
	}
	return nil
}

// FunctionHighorder takes a single unary function and lifts it to list level
// or processes the enumeration without a base function
// FunctionEnumerable can be used both on list element and enumeration stream
type FunctionEnumerable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fn *Function `protobuf:"bytes,2,opt,name=fn,proto3" json:"fn,omitempty"`
}

func (x *FunctionEnumerable) Reset() {
	*x = FunctionEnumerable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionEnumerable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionEnumerable) ProtoMessage() {}

func (x *FunctionEnumerable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionEnumerable.ProtoReflect.Descriptor instead.
func (*FunctionEnumerable) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionEnumerable) GetFn() *Function {
	if x != nil {
		return x.Fn
	}
	return nil
}

type Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Fn:
	//	*Function_Numeric
	//	*Function_SelectField
	//	*Function_Sequence
	//	*Function_Enumerable
	Fn isFunction_Fn `protobuf_oneof:"fn"`
}

func (x *Function) Reset() {
	*x = Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{7}
}

func (m *Function) GetFn() isFunction_Fn {
	if m != nil {
		return m.Fn
	}
	return nil
}

func (x *Function) GetNumeric() *FunctionNumeric {
	if x, ok := x.GetFn().(*Function_Numeric); ok {
		return x.Numeric
	}
	return nil
}

func (x *Function) GetSelectField() *FunctionSelectField {
	if x, ok := x.GetFn().(*Function_SelectField); ok {
		return x.SelectField
	}
	return nil
}

func (x *Function) GetSequence() *FunctionSequence {
	if x, ok := x.GetFn().(*Function_Sequence); ok {
		return x.Sequence
	}
	return nil
}

func (x *Function) GetEnumerable() *FunctionEnumerable {
	if x, ok := x.GetFn().(*Function_Enumerable); ok {
		return x.Enumerable
	}
	return nil
}

type isFunction_Fn interface {
	isFunction_Fn()
}

type Function_Numeric struct {
	Numeric *FunctionNumeric `protobuf:"bytes,1,opt,name=numeric,proto3,oneof"`
}

type Function_SelectField struct {
	SelectField *FunctionSelectField `protobuf:"bytes,2,opt,name=selectField,proto3,oneof"`
}

type Function_Sequence struct {
	Sequence *FunctionSequence `protobuf:"bytes,3,opt,name=sequence,proto3,oneof"`
}

type Function_Enumerable struct {
	Enumerable *FunctionEnumerable `protobuf:"bytes,4,opt,name=enumerable,proto3,oneof"`
}

func (*Function_Numeric) isFunction_Fn() {}

func (*Function_SelectField) isFunction_Fn() {}

func (*Function_Sequence) isFunction_Fn() {}

func (*Function_Enumerable) isFunction_Fn() {}

type QueryOperator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fn *FunctionEnumerable `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
}

func (x *QueryOperator) Reset() {
	*x = QueryOperator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOperator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOperator) ProtoMessage() {}

func (x *QueryOperator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOperator.ProtoReflect.Descriptor instead.
func (*QueryOperator) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{8}
}

func (x *QueryOperator) GetFn() *FunctionEnumerable {
	if x != nil {
		return x.Fn
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ops []*QueryOperator `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRequest) GetOps() []*QueryOperator {
	if x != nil {
		return x.Ops
	}
	return nil
}

type BytesState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BytesState) Reset() {
	*x = BytesState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesState) ProtoMessage() {}

func (x *BytesState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesState.ProtoReflect.Descriptor instead.
func (*BytesState) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{10}
}

func (x *BytesState) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BytesState) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BytesEnumarable []*BytesState `protobuf:"bytes,1,rep,name=bytesEnumarable,proto3" json:"bytesEnumarable,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_operation_proto_rawDescGZIP(), []int{11}
}

func (x *QueryResponse) GetBytesEnumarable() []*BytesState {
	if x != nil {
		return x.BytesEnumarable
	}
	return nil
}

var File_proto_operation_proto protoreflect.FileDescriptor

var file_proto_operation_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x41, 0x0a, 0x07, 0x55, 0x69, 0x6e, 0x74, 0x32,
	0x35, 0x36, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x01, 0x61,
	0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x01, 0x62, 0x12, 0x0c,
	0x0a, 0x01, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06, 0x52, 0x01, 0x64, 0x22, 0x40, 0x0a, 0x06, 0x49, 0x6e,
	0x74, 0x32, 0x35, 0x36, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x01, 0x62,
	0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x01, 0x63, 0x12, 0x0c,
	0x0a, 0x01, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06, 0x52, 0x01, 0x64, 0x22, 0x83, 0x01, 0x0a,
	0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x2c, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35,
	0x36, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x63,
	0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x69, 0x6e, 0x74,
	0x32, 0x35, 0x36, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x5f,
	0x69, 0x64, 0x22, 0xa3, 0x03, 0x0a, 0x0f, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x44, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0d,
	0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0d, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x41, 0x0a, 0x0e, 0x55, 0x69,
	0x6e, 0x74, 0x32, 0x35, 0x36, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x48, 0x00, 0x52, 0x0e, 0x55,
	0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x3e, 0x0a,
	0x0d, 0x49, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x48, 0x00, 0x52, 0x0d,
	0x49, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x22, 0x6e, 0x0a,
	0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x53, 0x55, 0x42, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x55, 0x4c, 0x10,
	0x03, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x56, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x54,
	0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10, 0x06, 0x12, 0x06, 0x0a, 0x02, 0x47,
	0x54, 0x10, 0x07, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x45, 0x10, 0x08, 0x12, 0x06, 0x0a, 0x02,
	0x45, 0x51, 0x10, 0x09, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x51, 0x10, 0x0a, 0x42, 0x09, 0x0a,
	0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x22, 0x55, 0x0a, 0x13, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x3c, 0x0a, 0x10, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x02, 0x66, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x66, 0x6e, 0x22, 0xac, 0x01,
	0x0a, 0x12, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x02, 0x66, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x66, 0x6e, 0x22, 0x6c,
	0x0a, 0x0c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d,
	0x41, 0x50, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x46, 0x4f, 0x4c, 0x44, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x41,
	0x4b, 0x45, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x41, 0x4b, 0x45, 0x57, 0x48, 0x49, 0x4c,
	0x45, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x52, 0x4f, 0x50, 0x10, 0x06, 0x12, 0x0d, 0x0a,
	0x09, 0x44, 0x52, 0x4f, 0x50, 0x57, 0x48, 0x49, 0x4c, 0x45, 0x10, 0x07, 0x22, 0x9c, 0x02, 0x0a,
	0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x07, 0x6e, 0x75, 0x6d,
	0x65, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x62, 0x63,
	0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x48, 0x00, 0x52, 0x07, 0x6e,
	0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x47, 0x0a, 0x0b, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x62,
	0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x3e, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x44, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75,
	0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x65,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x04, 0x0a, 0x02, 0x66, 0x6e, 0x22, 0x43, 0x0a, 0x0d, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x02,
	0x66, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x02, 0x66, 0x6e,
	0x22, 0x3f, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2f, 0x0a, 0x03, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x03, 0x6f, 0x70,
	0x73, 0x22, 0x34, 0x0a, 0x0a, 0x42, 0x79, 0x74, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x55, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x45, 0x6e, 0x75, 0x6d, 0x61, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x61, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x32, 0x54,
	0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44,
	0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1c, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x62, 0x63, 0x69, 0x2e, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x63, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x2f, 0x64, 0x62, 0x63, 0x69, 0x2f,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_operation_proto_rawDescOnce sync.Once
	file_proto_operation_proto_rawDescData = file_proto_operation_proto_rawDesc
)

func file_proto_operation_proto_rawDescGZIP() []byte {
	file_proto_operation_proto_rawDescOnce.Do(func() {
		file_proto_operation_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_operation_proto_rawDescData)
	})
	return file_proto_operation_proto_rawDescData
}

var file_proto_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_operation_proto_goTypes = []interface{}{
	(FunctionNumeric_Operator)(0),        // 0: dbci.operation.FunctionNumeric.Operator
	(FunctionEnumerable_FunctionType)(0), // 1: dbci.operation.FunctionEnumerable.FunctionType
	(*Uint256)(nil),                      // 2: dbci.operation.Uint256
	(*Int256)(nil),                       // 3: dbci.operation.Int256
	(*Asset)(nil),                        // 4: dbci.operation.Asset
	(*FunctionNumeric)(nil),              // 5: dbci.operation.FunctionNumeric
	(*FunctionSelectField)(nil),          // 6: dbci.operation.FunctionSelectField
	(*FunctionSequence)(nil),             // 7: dbci.operation.FunctionSequence
	(*FunctionEnumerable)(nil),           // 8: dbci.operation.FunctionEnumerable
	(*Function)(nil),                     // 9: dbci.operation.Function
	(*QueryOperator)(nil),                // 10: dbci.operation.QueryOperator
	(*QueryRequest)(nil),                 // 11: dbci.operation.QueryRequest
	(*BytesState)(nil),                   // 12: dbci.operation.BytesState
	(*QueryResponse)(nil),                // 13: dbci.operation.QueryResponse
}
var file_proto_operation_proto_depIdxs = []int32{
	2,  // 0: dbci.operation.Asset.id:type_name -> dbci.operation.Uint256
	2,  // 1: dbci.operation.Asset.amount:type_name -> dbci.operation.Uint256
	0,  // 2: dbci.operation.FunctionNumeric.operator:type_name -> dbci.operation.FunctionNumeric.Operator
	2,  // 3: dbci.operation.FunctionNumeric.Uint256Operand:type_name -> dbci.operation.Uint256
	3,  // 4: dbci.operation.FunctionNumeric.Int256Operand:type_name -> dbci.operation.Int256
	9,  // 5: dbci.operation.FunctionSequence.fn:type_name -> dbci.operation.Function
	9,  // 6: dbci.operation.FunctionEnumerable.fn:type_name -> dbci.operation.Function
	5,  // 7: dbci.operation.Function.numeric:type_name -> dbci.operation.FunctionNumeric
	6,  // 8: dbci.operation.Function.selectField:type_name -> dbci.operation.FunctionSelectField
	7,  // 9: dbci.operation.Function.sequence:type_name -> dbci.operation.FunctionSequence
	8,  // 10: dbci.operation.Function.enumerable:type_name -> dbci.operation.FunctionEnumerable
	8,  // 11: dbci.operation.QueryOperator.fn:type_name -> dbci.operation.FunctionEnumerable
	10, // 12: dbci.operation.QueryRequest.ops:type_name -> dbci.operation.QueryOperator
	12, // 13: dbci.operation.QueryResponse.bytesEnumarable:type_name -> dbci.operation.BytesState
	11, // 14: dbci.operation.QueryService.Query:input_type -> dbci.operation.QueryRequest
	13, // 15: dbci.operation.QueryService.Query:output_type -> dbci.operation.QueryResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_operation_proto_init() }
func file_proto_operation_proto_init() {
	if File_proto_operation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_operation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uint256); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int256); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionNumeric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionSelectField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionSequence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionEnumerable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOperator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_operation_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_proto_operation_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*FunctionNumeric_Uint64Operand)(nil),
		(*FunctionNumeric_Int64Operand)(nil),
		(*FunctionNumeric_Uint256Operand)(nil),
		(*FunctionNumeric_Int256Operand)(nil),
	}
	file_proto_operation_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Function_Numeric)(nil),
		(*Function_SelectField)(nil),
		(*Function_Sequence)(nil),
		(*Function_Enumerable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_operation_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_operation_proto_goTypes,
		DependencyIndexes: file_proto_operation_proto_depIdxs,
		EnumInfos:         file_proto_operation_proto_enumTypes,
		MessageInfos:      file_proto_operation_proto_msgTypes,
	}.Build()
	File_proto_operation_proto = out.File
	file_proto_operation_proto_rawDesc = nil
	file_proto_operation_proto_goTypes = nil
	file_proto_operation_proto_depIdxs = nil
}
